// HDR starfield in octahedral parameterisation, plus a procedural Milky Way.
//
// Stars are generated by hashing a jittered grid in octahedral (u,v) space.
// That keeps the *angular* density uniform to within a few percent — a naive
// spherical-angle hash clusters badly at the poles — and it means the field can
// be regenerated at any resolution from a single seed.  Blackbody colours come
// straight from the Planck locus; magnitudes follow a power law, so a handful
// of super-bright stars dominate exactly as they do in the real sky.
precision highp float;

#include <shared>

varying vec3 vDir;

uniform float uDensity;      // stars per octahedral cell (scaled by resolution)
uniform float uBrightness;
uniform float uSeed;
uniform float uNebula;
uniform float uMilkyWay;     // 0..1 visibility of the galactic band
uniform mat3 uGalacticBasis;

// Octahedral mapping: a direction becomes a point in the unit square.
vec2 octEncode(vec3 n) {
  n /= (abs(n.x) + abs(n.y) + abs(n.z));
  vec2 uv = n.xy;
  if (n.z < 0.0) uv = (1.0 - abs(n.yx)) * sign(n.xy + 1e-6);
  return uv * 0.5 + 0.5;
}

vec3 octDecode(vec2 uv) {
  uv = uv * 2.0 - 1.0;
  vec3 n = vec3(uv.x, uv.y, 1.0 - abs(uv.x) - abs(uv.y));
  float t = max(-n.z, 0.0);
  n.x += n.x >= 0.0 ? -t : t;
  n.y += n.y >= 0.0 ? -t : t;
  return normalize(n);
}

/** One cell of the star grid: returns (rgb, coverage). */
void starCell(vec2 cell, vec2 uv, float cells, inout vec3 color) {
  vec3 h = hash33(vec3(cell, uSeed));
  if (h.x > uDensity) return;
  vec2 sub = vec2(h.y, h.z);
  vec2 delta = (sub - uv) * cells;
  float r2 = dot(delta, delta);
  float radius = mix(0.008, 0.055, pow(h.x / max(uDensity, 1e-5), 3.0));
  float mask = exp(-r2 / (radius * radius * 2.0));
  // Spectral class from a power-law magnitude distribution.
  float m = pow(fract(h.x * 71.3 + h.y * 13.7), 3.0);
  float temp = mix(2600.0, 22000.0, pow(fract(h.y * 91.7 + h.z * 7.3), 1.6));
  vec3 tint = blackbody(temp);
  color += tint * mask * uBrightness * (0.6 + 34.0 * m);
}

void main() {
  vec3 dir = normalize(vDir);
  vec3 color = vec3(0.0);

  // Two shells: a dense faint layer for the Milky Way's unresolved stars and a
  // sparse bright layer for naked-eye stars.
  const float RES = 512.0;
  vec2 uv = octEncode(dir);
  vec2 g = uv * RES;
  vec2 cell = floor(g);
  for (int dy = -1; dy <= 1; dy++) {
    for (int dx = -1; dx <= 1; dx++) {
      starCell(cell + vec2(float(dx), float(dy)), uv, RES, color);
    }
  }
  // Bright-star shell on a coarser grid, so a few stars outshine the rest.
  const float RES2 = 96.0;
  vec2 g2 = uv * RES2;
  vec2 c2 = floor(g2);
  for (int dy = -1; dy <= 1; dy++) {
    for (int dx = -1; dx <= 1; dx++) {
      starCell(c2 + vec2(float(dx), float(dy)) + vec2(0.5), uv, RES2, color);
    }
  }

  // Milky Way: a band of unresolved light along the galactic plane, with dust
  // lanes carved out by fbm.
  vec3 gal = uGalacticBasis * dir;
  float band = exp(-pow(abs(gal.y) * 6.5, 1.7));
  float dust = fbm(dir * 7.0 + uSeed * 3.0, 6, 2.1, 0.55);
  float clumps = fbm(dir * 22.0 - 4.0, 5, 2.0, 0.5);
  vec3 bandColor = mix(vec3(0.16, 0.17, 0.26), vec3(0.34, 0.28, 0.22), dust) * 0.75;
  color += bandColor * band * (0.45 + 0.9 * clumps) * uMilkyWay * 18.0;
  color += vec3(0.03, 0.04, 0.07) * band * uMilkyWay;

  // Faint nebular emission.
  float neb = pow(max(fbm(dir * 3.5 + 8.0, 5, 2.2, 0.5), 0.0), 2.5);
  vec3 nebColor = mix(vec3(0.35, 0.08, 0.22), vec3(0.05, 0.18, 0.32), fract(uSeed * 0.37));
  color += nebColor * neb * uNebula * 6.0;

  // Faint extra-galactic background so deep space is never pure black.
  color += vec3(0.0016, 0.0018, 0.0030);
  gl_FragColor = vec4(color, 1.0);
}
