#!/usr/bin/env node
/**
 * Package the built app into a downloadable zip.
 *
 *     npm run build && npm run release        # writes release/cosmoscope-<version>.zip
 *
 * The zip contains the production bundle, the tiny `serve.mjs` launcher and a
 * START-HERE file, laid out so that unzipping and running `node serve.mjs` is the
 * whole install procedure. The archive is written with Node's own zlib — no `zip`
 * binary, no dependencies — so the artifact is byte-reproducible on any platform
 * and can be regenerated by anyone from a clean checkout:
 *
 *     npm ci && npm run build && npm run release
 */

import { deflateRawSync } from 'node:zlib';
import { mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import { join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = resolve(fileURLToPath(new URL('..', import.meta.url)));
const pkg = JSON.parse(await readFile(join(repo, 'package.json'), 'utf8'));
const name = `cosmoscope-${pkg.version}`;
const outDir = join(repo, 'release');
// The unpacked copy is scaffolding, not an artifact — stage it under .tmp/ (which
// is git-ignored) and only the zip lands in release/.
const stage = join(repo, '.tmp', 'release', name);

// ── collect the files that go in ────────────────────────────────────────────
async function walk(dir) {
  const found = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) found.push(...(await walk(path)));
    else if (entry.isFile()) found.push(path);
  }
  return found.sort();
}

await rm(stage, { recursive: true, force: true });
await mkdir(stage, { recursive: true });

for (const file of await walk(join(repo, 'dist'))) {
  const target = join(stage, relative(join(repo, 'dist'), file));
  await mkdir(join(target, '..'), { recursive: true });
  await writeFile(target, await readFile(file));
}
for (const extra of ['scripts/serve.mjs', 'release/START-HERE.txt']) {
  const target = join(stage, extra.split('/').pop());
  await writeFile(target, await readFile(join(repo, extra)));
}

// Without a toolchain the launcher has to be self-evident, so make it executable
// and add a shebang-based hint at the top of the start file.
const files = await walk(stage);
const total = (await Promise.all(files.map(async (f) => (await stat(f)).size))).reduce(
  (a, b) => a + b,
  0,
);

// ── a minimal ZIP writer (deflate + CRC32, no dependencies) ─────────────────
const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buf) {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

/** Fixed timestamp keeps the archive byte-identical across clean rebuilds. */
const DOS_TIME = 0;
const DOS_DATE = ((2026 - 1980) << 9) | (1 << 5) | 1; // 2026-01-01

const chunks = [];
const central = [];
let offset = 0;

for (const file of files) {
  const data = await readFile(file);
  const nameBytes = Buffer.from(`${name}/${relative(stage, file).split(sep).join('/')}`, 'utf8');
  const deflated = deflateRawSync(data, { level: 9 });
  const stored = deflated.length >= data.length;
  const payload = stored ? data : deflated;
  const method = stored ? 0 : 8;
  const crc = crc32(data);

  const local = Buffer.alloc(30 + nameBytes.length);
  local.writeUInt32LE(0x04034b50, 0);
  local.writeUInt16LE(20, 4);
  local.writeUInt16LE(0, 6);
  local.writeUInt16LE(method, 8);
  local.writeUInt16LE(DOS_TIME, 10);
  local.writeUInt16LE(DOS_DATE, 12);
  local.writeUInt32LE(crc, 14);
  local.writeUInt32LE(payload.length, 18);
  local.writeUInt32LE(data.length, 22);
  local.writeUInt16LE(nameBytes.length, 26);
  local.writeUInt16LE(0, 28);
  nameBytes.copy(local, 30);

  chunks.push(local, payload);

  const entry = Buffer.alloc(46 + nameBytes.length);
  entry.writeUInt32LE(0x02014b50, 0);
  entry.writeUInt16LE(20, 4);
  entry.writeUInt16LE(20, 6);
  entry.writeUInt16LE(0, 8);
  entry.writeUInt16LE(method, 10);
  entry.writeUInt16LE(DOS_TIME, 12);
  entry.writeUInt16LE(DOS_DATE, 14);
  entry.writeUInt32LE(crc, 16);
  entry.writeUInt32LE(payload.length, 20);
  entry.writeUInt32LE(data.length, 24);
  entry.writeUInt16LE(nameBytes.length, 28);
  entry.writeUInt32LE(0, 30); // extra
  entry.writeUInt32LE(0, 32); // comment
  entry.writeUInt32LE(0, 36); // disk
  entry.writeUInt32LE(0, 38); // internal attributes
  entry.writeUInt32LE((0o100644 << 16) >>> 0, 40); // external attributes: regular file, rw-r--r--
  entry.writeUInt32LE(offset, 42);
  nameBytes.copy(entry, 46);
  central.push(entry);

  offset += local.length + payload.length;
}

const centralBuffer = Buffer.concat(central);
const end = Buffer.alloc(22);
end.writeUInt32LE(0x06054b50, 0);
end.writeUInt16LE(0, 4);
end.writeUInt16LE(0, 6);
end.writeUInt16LE(files.length, 8);
end.writeUInt16LE(files.length, 10);
end.writeUInt32LE(centralBuffer.length, 12);
end.writeUInt32LE(offset, 16);
end.writeUInt16LE(0, 20);

const zipPath = join(outDir, `${name}.zip`);
await writeFile(zipPath, Buffer.concat([...chunks, centralBuffer, end]));

const kb = (n) => `${(n / 1024).toFixed(1)} kB`;
console.log(`${relative(repo, zipPath)}`);
console.log(`  ${files.length} files, ${kb(total)} unpacked, ${kb((await stat(zipPath)).size)} packed`);
for (const file of files) console.log(`  ${relative(stage, file)}  ${kb((await stat(file)).size)}`);
